spring:
  cloud: 
   gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"   
      routes:
      - id: servHoteles #Id de la ruta 
        uri: lb://viajes-hoteles
        predicates:
          - Path=/shoteles/** #Cuando Gateway detecte que en la peticion URL venga este path, enrutara la peticion hacia el servicio indicado en la propiedad "uri" (lb://cliente-cursos)
        filters:
          - RewritePath=/shoteles/*, / #Lo que indica es que a la url indicada en la propiedad "uri", se le adicionará un "/" mas todo lo que venga despues de "sformaciones" en la petición URL de entrada
      - id: servVuelos #Id de la ruta 
        uri: lb://viajes-vuelos
        predicates:
          - Path=/svuelos/** #Cuando Gateway detecte que en la peticion URL venga este path, enrutara la peticion hacia el servicio indicado en la propiedad "uri" (lb://cliente-cursos)
        filters:
          - RewritePath=/svuelos/*, / #Lo que indica es que a la url indicada en la propiedad "uri", se le adicionará un "/" mas todo lo que venga despues de "sformaciones" en la petición URL de entrada
      - id: servReservas #Id de la ruta 
        uri: lb://viajes-reservas
        predicates:
          - Path=/sreservas/** #Cuando Gateway detecte que en la peticion URL venga este path, enrutara la peticion hacia el servicio indicado en la propiedad "uri" (lb://cliente-cursos)
        filters:
          - RewritePath=/sreservas/*, / #Lo que indica es que a la url indicada en la propiedad "uri", se le adicionará un "/" mas todo lo que venga despues de "sformaciones" en la petición URL de entrada
server:
  port: 9000
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka



