#Acceso a BD
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.43.170:3306/cursotrainingit?serverTimezone=UTC
    username: root
    password: root
#Instrucciones SQL
  jpa: 
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    context-path: /viajes
#Documentacion
springdoc:
  packagesToScan: com.controller
  pathsToMatch: /**
# Registro/descubrimiento 
eureka: 
  client:
    serviceUrl:
      defaultZone: http://192.168.43.170:9761/eureka 
  instance:
    hostname: 192.168.43.170 # Necesaria para que el Gateway lo localice a través su registro en Eureka (IP de la máquina donde residirá)         
# Instancias
    # Instancia 1
    instance-id=instancia_01
    # Instancia 2
    #instance-id=instancia_02
server:
  port: 8101 #Instancia 1
  #port: 8102 #Instancia 2
  
