#Acceso a BD
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.156:3306/cursotrainingit?serverTimezone=UTC
    username: root
    password: root
# Instrucciones SQL
  jpa: 
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8081
  servlet:
    context-path: /viajes
# Documentacion
springdoc:
  packagesToScan: com.controller
  pathsToMatch: /**
# Registro/descubrimiento 
eureka: 
  client:
    service-url:
      defaultZone=http://localhost:9261/eureka
      #defaultZone=http://localhost:8761/eureka
      #defaultZone=http://localhost:9999/eureka
